rtx.fallbackLightRadius = 0.03
rtx.neuralRadianceCache.trainingMaxPathBounces = 7
rtx.ignoreTextures = 0x0F20E248AAA2B328, 0xF191C97F67B7E256
rtx.worldSpaceUiTextures = 0x46265996825A1CAA, 0x48EB4FC0A2B46391
rtx.enableFirstBounceLobeProbabilityDithering = False
rtx.fallbackLightType = 1
rtx.playerModelTextures = 0x165F453A5F35C459, 0x55A580C5566E9734
rtx.antiCulling.light.enable = True
rtx.neuralRadianceCache.qualityPreset = 1
rtx.lightmapTextures = 0x4052929624B32710, 0xAABCCBF7FC3F8C75, 0xB2930BA4E90029B8
rtx.minOpaqueSpecularLobeSamplingProbability = 0.05
rtx.volumetrics.enable = False
rtx.di.stealBoundaryPixelSamplesWhenOutsideOfScreen = False
rtx.fallbackLightMode = 2
rtx.enableFog = False
rtx.decalTextures = 0x21C4D28D688E888B, 0x2E7DB7A51BEB08CB, 0x342A7D68A411DD4F, 0x366BBF371266D284, 0x8330F4B0CE25BF6A, 0xA3A98280E645FC93
rtx.di.initialSampleCount = 3
rtx.pathMaxBounces = 2
rtx.enableTransmissionApproximationInIndirectRays = True
rtx.neuralRadianceCache.terminationHeuristicThreshold = 0.03
rtx.postFilterThreshold = 10
rtx.volumetrics.froxelDepthSlices = 48
rtx.neuralRadianceCache.smallestResolvableFeatureSizeMeters = 0.04
rtx.neuralRadianceCache.targetNumTrainingIterations = 3
rtx.defaultToAdvancedUI = True
rtx.pathMinBounces = 0
rtx.denoiseDirectAndIndirectLightingSeparately = False
rtx.minOpaqueDiffuseLobeSamplingProbability = 0.05
rtx.replaceDirectSpecularHitTWithIndirectSpecularHitT = False
rtx.di.enableDenoiserConfidence = False
rtx.antiCulling.object.enable = True
rtx.russianRouletteMode = 1
rtx.di.disocclusionSamples = 2
rtx.di.permutationSamplingNthFrame = 1
rtx.di.enableBestLightSampling = False
rtx.particleTextures = 0x0A53067F417EE6E5, 0x17998081C91B8293, 0x3F7BF2A09EA4FA4C, 0x443AE605858B972A, 0xBE5791C0013635D3
rtx.demodulate.enableDirectLightBoilingFilter = False
rtx.graphicsPreset = 1
rtx.di.enableSampleStealing = False
rtx.neeCache.enableModeAfterFirstBounce = 2
rtx.usePostFilter = False
rtx.raytracedRenderTargetTextures = 0x292114A87F742BB1
rtx.antiCulling.object.enableInfinityFarFrustum = True
